import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import chalk from 'chalk';
import { runPreflight, type PreflightResult, type ProviderStatus } from './preflight.js';
import { writeConfig, DEFAULTS } from './config.js';
import { printLogo } from './display/quetz.js';
import type { QuetzConfig } from './config.js';
import { runAgent } from './agent.js';
import { getProviderDescriptor } from './provider.js';

const AUTOMERGE_TEMPLATE = `# .github/workflows/quetz-automerge.yml
# Generated by quetz init
name: Auto-merge on checks pass

on:
  check_suite:
    types: [completed]
  pull_request_review:
    types: [submitted]
  status: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request != null ||
      github.event.check_suite != null ||
      github.event.state != null
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge labelled PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "{{automergeLabel}}"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_METHOD: "rebase"
`;

function section(title: string): void {
  process.stdout.write(`\n${chalk.bold(title)}\n`);
  process.stdout.write(`${chalk.gray('-'.repeat(title.length))}\n\n`);
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve));
}

async function promptConfirm(rl: readline.Interface, label: string, defaultValue: string): Promise<string> {
  const prompt = `  ${chalk.cyan(label)}  ${chalk.gray(`[${defaultValue}]`)}: `;
  const answer = await ask(rl, prompt);
  return answer.trim() || defaultValue;
}

async function gatherConfig(rl: readline.Interface, preflight: PreflightResult): Promise<QuetzConfig> {
  let { owner, repo, defaultBranch } = preflight;

  section('Config Setup');

  owner = await promptConfirm(rl, 'GitHub owner/org', owner || 'owner');
  repo = await promptConfirm(rl, 'GitHub repo', repo || 'repo');
  defaultBranch = await promptConfirm(rl, 'Default branch', defaultBranch || 'main');
  const automergeLabel = await promptConfirm(rl, 'Automerge label', DEFAULTS.github.automergeLabel);

  return {
    ...DEFAULTS,
    github: { owner, repo, defaultBranch, automergeLabel },
    agent: {
      ...DEFAULTS.agent,
      provider: preflight.preferredProvider,
      model: getProviderDescriptor(preflight.preferredProvider).defaultModel,
    },
  };
}

function getAutomergeYaml(automergeLabel: string): string {
  return AUTOMERGE_TEMPLATE.replace('{{automergeLabel}}', automergeLabel);
}

async function runWorkflowAgent(providerId: PreflightResult['preferredProvider'], prompt: string, projectRoot: string): Promise<void> {
  const exitCode = await runAgent({
    provider: providerId,
    prompt,
    cwd: projectRoot,
    model: getProviderDescriptor(providerId).defaultModel,
    timeoutMinutes: DEFAULTS.agent.timeout,
  });

  if (exitCode !== 0) {
    throw new Error(`${getProviderDescriptor(providerId).displayName} exited with code ${exitCode}`);
  }
}

async function setupGitHubActions(
  rl: readline.Interface,
  config: QuetzConfig,
  projectRoot: string,
  preferredProvider: PreflightResult['preferredProvider']
): Promise<void> {
  const yaml = getAutomergeYaml(config.github.automergeLabel);
  const provider = getProviderDescriptor(preferredProvider);

  section('GitHub Actions Setup');
  process.stdout.write(
    '  Quetz needs one GitHub Action: an automerge workflow that merges PRs\n' +
    `  when all checks pass and the ${chalk.cyan(`"${config.github.automergeLabel}"`)} label is present.\n\n` +
    `  ${chalk.bold('[1]')}  Write workflow to ${chalk.gray('.github/workflows/quetz-automerge.yml')}\n` +
    `  ${chalk.bold('[2]')}  Have ${provider.displayName} raise a PR to add it\n` +
    `  ${chalk.bold('[3]')}  I'll handle it myself ${chalk.gray('(show me the YAML)')}\n\n`
  );

  const choice = await ask(rl, '  Select [1/2/3]: ');

  if (choice.trim() === '1') {
    const workflowDir = path.join(projectRoot, '.github', 'workflows');
    fs.mkdirSync(workflowDir, { recursive: true });
    fs.writeFileSync(path.join(workflowDir, 'quetz-automerge.yml'), yaml, 'utf-8');
    process.stdout.write(`\n  ${chalk.green('OK')}  Wrote .github/workflows/quetz-automerge.yml\n`);
    return;
  }

  if (choice.trim() === '2') {
    const prompt =
      'Create the file .github/workflows/quetz-automerge.yml with the following content:\n\n' +
      yaml +
      '\n\nCommit it, push to a new branch, and open a pull request.';
    try {
      await runWorkflowAgent(preferredProvider, prompt, projectRoot);
    } catch {
      process.stderr.write(`\n${provider.displayName} session ended.\n`);
    }
    return;
  }

  process.stdout.write('\n  Paste this into .github/workflows/quetz-automerge.yml:\n\n');
  process.stdout.write(`${yaml}\n`);
}

function printLabelReminder(config: QuetzConfig): void {
  process.stdout.write(
    `\n  ${chalk.yellow('!')}  Create the ${chalk.cyan(`"${config.github.automergeLabel}"`)} label on your GitHub repo:\n` +
    `${chalk.gray(`     https://github.com/${config.github.owner}/${config.github.repo}/labels`)}\n` +
    '     Quetz agents will tag PRs with this label to trigger auto-merge.\n'
  );
}

function formatProviderChecklistLine(status: ProviderStatus, preferredProvider: PreflightResult['preferredProvider']): string {
  const descriptor = getProviderDescriptor(status.provider);
  const selected = status.provider === preferredProvider ? ' (selected)' : '';

  if (!status.installed) {
    return `  ${chalk.red('✗')}  ${descriptor.displayName}: ${descriptor.runtime.unavailableLabel}${selected}`;
  }

  if (!status.authenticated) {
    return `  ${chalk.red('✗')}  ${descriptor.displayName}: installed, not authenticated${selected}`;
  }

  if (!status.runtimeImplemented) {
    return `  ${chalk.red('✗')}  ${descriptor.displayName}: authenticated, runtime unavailable${selected}`;
  }

  return `  ${chalk.green('✓')}  ${descriptor.displayName}: ready${selected}`;
}

export function formatPreflightChecklist(preflight: PreflightResult): string[] {
  return [
    `  ${chalk.green('✓')}  GitHub CLI authenticated`,
    `  ${chalk.green('✓')}  Beads CLI ready`,
    `  ${chalk.green('✓')}  Git remote origin -> ${preflight.owner}/${preflight.repo} (${preflight.defaultBranch})`,
    ...preflight.providerStatuses.map(status => formatProviderChecklistLine(status, preflight.preferredProvider)),
  ];
}

export async function runInit(projectRoot: string = process.cwd()): Promise<void> {
  printLogo();

  section('Preflight Checks');
  const preflight = runPreflight();
  for (const line of formatPreflightChecklist(preflight)) {
    process.stdout.write(`${line}\n`);
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    const config = await gatherConfig(rl, preflight);
    writeConfig(config, projectRoot);
    process.stdout.write(`\n  ${chalk.green('OK')}  Wrote .quetzrc.yml\n`);

    await setupGitHubActions(rl, config, projectRoot, preflight.preferredProvider);
    printLabelReminder(config);

    process.stdout.write(`\n${chalk.green.bold('Ready.')}  Run ${chalk.cyan('quetz run')} to start the loop.\n\n`);
  } finally {
    rl.close();
  }
}
