import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { execSync } from 'child_process';
import chalk from 'chalk';
import { runPreflight } from './preflight.js';
import { writeConfig, DEFAULTS } from './config.js';
import { printLogo } from './display/quetz.js';
import type { QuetzConfig } from './config.js';

const AUTOMERGE_TEMPLATE = `# .github/workflows/quetz-automerge.yml
# Generated by quetz init
name: Auto-merge on checks pass

on:
  check_suite:
    types: [completed]
  pull_request_review:
    types: [submitted]
  status: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request != null ||
      github.event.check_suite != null ||
      github.event.state != null
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge labelled PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "{{automergeLabel}}"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_METHOD: "rebase"
`;

function section(title: string): void {
  process.stdout.write('\n' + chalk.bold(title) + '\n');
  process.stdout.write(chalk.gray('─'.repeat(title.length)) + '\n\n');
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve));
}

async function promptConfirm(
  rl: readline.Interface,
  label: string,
  defaultVal: string
): Promise<string> {
  const prompt = `  ${chalk.cyan(label)}  ${chalk.gray('[' + defaultVal + ']')}: `;
  const answer = await ask(rl, prompt);
  return answer.trim() || defaultVal;
}

async function gatherConfig(rl: readline.Interface): Promise<QuetzConfig> {
  let { owner, repo, defaultBranch } = (() => {
    try {
      const { owner: o, repo: r, defaultBranch: b } = runPreflight();
      return { owner: o, repo: r, defaultBranch: b };
    } catch {
      return { owner: '', repo: '', defaultBranch: 'main' };
    }
  })();

  section('Config Setup');

  owner = await promptConfirm(rl, 'GitHub owner/org', owner || 'owner');
  repo = await promptConfirm(rl, 'GitHub repo', repo || 'repo');
  defaultBranch = await promptConfirm(rl, 'Default branch', defaultBranch || 'main');
  const automergeLabel = await promptConfirm(rl, 'Automerge label', DEFAULTS.github.automergeLabel);

  return {
    ...DEFAULTS,
    github: { owner, repo, defaultBranch, automergeLabel },
  };
}

function getAutomergeYaml(automergeLabel: string): string {
  return AUTOMERGE_TEMPLATE.replace('{{automergeLabel}}', automergeLabel);
}

async function setupGitHubActions(
  rl: readline.Interface,
  config: QuetzConfig,
  projectRoot: string
): Promise<void> {
  const yaml = getAutomergeYaml(config.github.automergeLabel);

  section('GitHub Actions Setup');
  process.stdout.write(
    '  Quetz needs one GitHub Action: an automerge workflow that merges PRs\n' +
    '  when all checks pass and the ' + chalk.cyan('"' + config.github.automergeLabel + '"') + ' label is present.\n\n' +
    '  ' + chalk.bold('[1]') + '  Write workflow to ' + chalk.gray('.github/workflows/quetz-automerge.yml') + '\n' +
    '  ' + chalk.bold('[2]') + '  Have Claude Code raise a PR to add it\n' +
    '  ' + chalk.bold('[3]') + '  I\'ll handle it myself ' + chalk.gray('(show me the YAML)') + '\n\n'
  );

  const choice = await ask(rl, '  Select [1/2/3]: ');

  if (choice.trim() === '1') {
    const workflowDir = path.join(projectRoot, '.github', 'workflows');
    fs.mkdirSync(workflowDir, { recursive: true });
    fs.writeFileSync(path.join(workflowDir, 'quetz-automerge.yml'), yaml, 'utf-8');
    process.stdout.write('\n  ' + chalk.green('✓') + '  Wrote .github/workflows/quetz-automerge.yml\n');
  } else if (choice.trim() === '2') {
    const prompt =
      'Create the file .github/workflows/quetz-automerge.yml with the following content:\n\n' +
      yaml +
      '\n\nCommit it, push to a new branch, and open a pull request.';
    try {
      execSync(`claude -p ${JSON.stringify(prompt)} --dangerously-skip-permissions`, {
        stdio: 'inherit',
        cwd: projectRoot,
      });
    } catch {
      process.stderr.write('\nClaude Code session ended.\n');
    }
  } else {
    process.stdout.write('\n  Paste this into .github/workflows/quetz-automerge.yml:\n\n');
    process.stdout.write(yaml + '\n');
  }
}

function printLabelReminder(config: QuetzConfig): void {
  process.stdout.write(
    '\n  ' + chalk.yellow('!') + '  Create the ' + chalk.cyan('"' + config.github.automergeLabel + '"') +
    ' label on your GitHub repo:\n' +
    chalk.gray('     https://github.com/' + config.github.owner + '/' + config.github.repo + '/labels') + '\n' +
    '     Quetz agents will tag PRs with this label to trigger auto-merge.\n'
  );
}

export async function runInit(projectRoot: string = process.cwd()): Promise<void> {
  printLogo();

  section('Preflight Checks');
  runPreflight();
  process.stdout.write('  ' + chalk.green('✓') + '  All checks passed.\n');

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    const config = await gatherConfig(rl);
    writeConfig(config, projectRoot);
    process.stdout.write('\n  ' + chalk.green('✓') + '  Wrote .quetzrc.yml\n');

    await setupGitHubActions(rl, config, projectRoot);
    printLabelReminder(config);

    process.stdout.write('\n' + chalk.green.bold('Ready.') + '  Run ' + chalk.cyan('quetz run') + ' to start the loop.\n\n');
  } finally {
    rl.close();
  }
}
